### ISSUE TITLE
Sign language integration

### ISSUE THREAD

**Issue by pratyaksh-dhairya-panwar** [pratyaksh-dhairya-panwar/voice-to-sign-language#1]
Currently, sign language is working while taking the input of voice. It should work simultaneously with sign language.
We also need to convert that text script into multiple languages.

**Comment by CodeGreatCommander** [comment]
@pratyaksh-dhairya-panwar check the coordination i have added a new branch

**Comment by CodeGreatCommander** [comment]
@pratyaksh-dhairya-panwar language feature added
